apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-server-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web-server
    spec:
      serviceAccountName: web-account
      containers:
      - name: web-server
        image: ityer/k8s-helm-http-wrapper:v4
        imagePullPolicy: Always
        ports:
        - containerPort: 4002
      imagePullSecrets:
        - name: deployment        