apiVersion: v1
kind: Service
metadata:
  name: web-server
  labels:
    app: web-server
spec:
  selector:
    app: web-server
  ports:
  - port: 4002
    protocol: TCP
    nodePort: 30101
  type: LoadBalancer