apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-server-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web-server
    spec:
      serviceAccountName: web-account
      containers:
      - name: web-server
        image: eladiwmicrosoft/helm-as-a-service:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 4002
        env:
        - name: LoadBalancerNamespace
          value: "ingress"
        - name: PortMin
          value: "20000"
        - name: PortMax
          value: "30000"
        - name: IngressLabel
          value: "ingress"
      imagePullSecrets:
        - name: deployment        