apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "port-service.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "port-service.name" . }}
    chart: {{ template "port-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "port-service.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "port-service.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.deployment.containerPort }}
              protocol: TCP
          env:
          - name: "LoadBalancerNamespace"
            value: {{ .Values.env.LoadBalancerNamespace }}
          - name: "PortMin"
            value: "{{ .Values.env.PortMin }}"
          - name: "PortMax"
            value: "{{ .Values.env.PortMax }}"
          - name: "IngressLabel"
            value: {{ .Values.env.IngressLabel }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.deployment.containerPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.deployment.containerPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
