apiVersion: v1
kind: Service
metadata:
  name: {{ template "port-service.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "port-service.name" . }}
    chart: {{ template "port-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ template "port-service.name" . }}
    release: {{ .Release.Name }}
