# Default values for autom8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ityer/autom8s
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 4000

namespace: default
ingressNamespace: default
  
