apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "autom8s.fullname" . }}
  labels:
    app: {{ template "autom8s.name" . }}
    chart: {{ template "autom8s.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "autom8s.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "autom8s.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.helmServiceAccount }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 4002
              protocol: TCP
          env:
          - name: LoadBalancerNamespace
            value: {{ .Values.ingressNamespace }}
          - name: PortMin
            value: "{{ .Values.minPort }}"
          - name: PortMax
            value: "{{ .Values.maxPort }}"
          - name: IngressLabel
            value: {{ .Values.ingressLabel }}
          - name: TILLER_SERVICE_ACCOUNT
            value: {{ .Values.tillerServiceAccount }}