apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-dashboard
  labels:
    k8s-app: kubernetes-dashboard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kubernetes-dashboard
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm
  namespace: {{ .Values.namespace }}
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: tiller-user
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - pods/portforward
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - list
  - get  
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: tiller-user-binding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tiller-user
subjects:
- kind: ServiceAccount
  name: helm
  namespace: {{ .Values.namespace }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "autom8s.fullname" . }}
  labels:
    app: {{ template "autom8s.name" . }}
    chart: {{ template "autom8s.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: 30101
      protocol: TCP
  selector:
    app: {{ template "autom8s.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "autom8s.fullname" . }}
  labels:
    app: {{ template "autom8s.name" . }}
    chart: {{ template "autom8s.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "autom8s.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "autom8s.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: helm
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 4002
              protocol: TCP
          env:
          - name: LoadBalancerNamespace
            value: "{{ .Values.ingressNamespace }}"
          - name: PortMin
            value: "20000"
          - name: PortMax
            value: "30000"
          - name: IngressLabel
            value: "ingress"
          - name: TILLER_SERVICE_ACCOUNT
            value: "tiller"
      imagePullSecrets:
        - name: deployment   