apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-service
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-service
    spec:
      containers:
      - name: sample-service
        image: ityer/k8s-deploy-service-sample:v3
        ports:
        - containerPort: 4009
        env:
        - name: LoadBalancerNamespace
          value: "ingress"
        - name: PortMin
          value: "20000"
        - name: PortMax
          value: "30000"
        - name: IngressLabel
          value: "ingress"
---
apiVersion: v1
kind: Service
metadata:
  name: sapmle-service
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 4009
    protocol: TCP
  selector:
    app: sample-service           